name: SmoothieBar
options:
  bundleIdPrefix: com.erkanozsoy
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.10"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
targets:
  SmoothieBar:
    type: application
    platform: iOS
    sources:
      - path: SmoothieBar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.erkanozsoy.smoothiebar
        DEVELOPMENT_TEAM: 9PJ9T53NSV
        PRODUCT_NAME: SmoothieBar
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: Smoothie Bar
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
